create table bank_account (id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=MyISAM;
create table bank_account_bank_transactions (bank_account_id bigint not null, bank_transactions_id bigint not null) engine=MyISAM;
create table transaction_app (id bigint not null auto_increment, transfered_amount float, date date not null, receiver_id bigint, sender_id bigint, primary key (id)) engine=MyISAM;
create table transaction_bank (id bigint not null auto_increment, transfered_amount float not null, date date not null, bank_account_id bigint, primary key (id)) engine=MyISAM;
create table user (id bigint not null auto_increment, amount_app_account float not null, email_adress varchar(255) not null, password varchar(255) not null, primary key (id)) engine=MyISAM;
create table user_bank_account (user_id bigint not null, bank_account_id bigint not null) engine=MyISAM;
create table user_contacts (user_id bigint not null, contacts_id bigint not null) engine=MyISAM;
create table user_transaction_users (user_id bigint not null, transaction_users_id bigint not null) engine=MyISAM;
alter table bank_account_bank_transactions add constraint UK_pgosd3tpquobn15aehke44j1g unique (bank_transactions_id);
alter table user_bank_account add constraint UK_n9nh18vaauto6bmi0p7ft8d4t unique (bank_account_id);
alter table user_transaction_users add constraint UK_6av3g4ea5w0lodnfhsp9d3l1c unique (transaction_users_id);
alter table bank_account add constraint FK92iik4jwhk7q385jubl2bc2mm foreign key (user_id) references user (id);
alter table bank_account_bank_transactions add constraint FK33paubx4rf8p5gj78h09r0k4u foreign key (bank_transactions_id) references transaction_bank (id);
alter table bank_account_bank_transactions add constraint FK93gtqw1lvfa10wpomw2yooxhs foreign key (bank_account_id) references bank_account (id);
alter table transaction_app add constraint FKf1gfaleqtl3di35sf0m8n2yiy foreign key (receiver_id) references user (id);
alter table transaction_app add constraint FK49j619uxo0m0p4ef9furm6hee foreign key (sender_id) references user (id);
alter table transaction_bank add constraint FKfsk86ieivf1trs79rd6huoxn3 foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FK32bq0igatas1bm9d7cj3emdmn foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FKjn71dv46t5vlrjbqroobqfxcl foreign key (user_id) references user (id);
alter table user_contacts add constraint FKbgjq1pj3f4kamou79l7cl87ne foreign key (contacts_id) references user (id);
alter table user_contacts add constraint FKmo0c5ro6kunnfq71x4bcwb9eh foreign key (user_id) references user (id);
alter table user_transaction_users add constraint FK7v441wsn0ldj19rgotmivv2tr foreign key (transaction_users_id) references transaction_app (id);
alter table user_transaction_users add constraint FKmjck60wbahp4thmrd6dd2gxiq foreign key (user_id) references user (id);
create table bank_account (id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=MyISAM;
create table bank_account_bank_transactions (bank_account_id bigint not null, bank_transactions_id bigint not null) engine=MyISAM;
create table transaction_app (id bigint not null auto_increment, transfered_amount float, date date not null, receiver_id bigint, sender_id bigint, primary key (id)) engine=MyISAM;
create table transaction_bank (id bigint not null auto_increment, transfered_amount float not null, date date not null, bank_account_id bigint, primary key (id)) engine=MyISAM;
create table user (id bigint not null auto_increment, amount_app_account float not null, email_adress varchar(255) not null, password varchar(255) not null, primary key (id)) engine=MyISAM;
create table user_bank_account (user_id bigint not null, bank_account_id bigint not null) engine=MyISAM;
create table user_contacts (user_id bigint not null, contacts_id bigint not null) engine=MyISAM;
create table user_transaction_users (user_id bigint not null, transaction_users_id bigint not null) engine=MyISAM;
alter table bank_account_bank_transactions add constraint UK_pgosd3tpquobn15aehke44j1g unique (bank_transactions_id);
alter table user_bank_account add constraint UK_n9nh18vaauto6bmi0p7ft8d4t unique (bank_account_id);
alter table user_transaction_users add constraint UK_6av3g4ea5w0lodnfhsp9d3l1c unique (transaction_users_id);
alter table bank_account add constraint FK92iik4jwhk7q385jubl2bc2mm foreign key (user_id) references user (id);
alter table bank_account_bank_transactions add constraint FK33paubx4rf8p5gj78h09r0k4u foreign key (bank_transactions_id) references transaction_bank (id);
alter table bank_account_bank_transactions add constraint FK93gtqw1lvfa10wpomw2yooxhs foreign key (bank_account_id) references bank_account (id);
alter table transaction_app add constraint FKf1gfaleqtl3di35sf0m8n2yiy foreign key (receiver_id) references user (id);
alter table transaction_app add constraint FK49j619uxo0m0p4ef9furm6hee foreign key (sender_id) references user (id);
alter table transaction_bank add constraint FKfsk86ieivf1trs79rd6huoxn3 foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FK32bq0igatas1bm9d7cj3emdmn foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FKjn71dv46t5vlrjbqroobqfxcl foreign key (user_id) references user (id);
alter table user_contacts add constraint FKbgjq1pj3f4kamou79l7cl87ne foreign key (contacts_id) references user (id);
alter table user_contacts add constraint FKmo0c5ro6kunnfq71x4bcwb9eh foreign key (user_id) references user (id);
alter table user_transaction_users add constraint FK7v441wsn0ldj19rgotmivv2tr foreign key (transaction_users_id) references transaction_app (id);
alter table user_transaction_users add constraint FKmjck60wbahp4thmrd6dd2gxiq foreign key (user_id) references user (id);
create table bank_account (id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=MyISAM;
create table bank_account_bank_transactions (bank_account_id bigint not null, bank_transactions_id bigint not null) engine=MyISAM;
create table transaction_app (id bigint not null auto_increment, transfered_amount float, date date not null, receiver_id bigint, sender_id bigint, primary key (id)) engine=MyISAM;
create table transaction_bank (id bigint not null auto_increment, transfered_amount float not null, date date not null, bank_account_id bigint, primary key (id)) engine=MyISAM;
create table user (id bigint not null auto_increment, amount_app_account float not null, email_adress varchar(255) not null, password varchar(255) not null, primary key (id)) engine=MyISAM;
create table user_bank_account (user_id bigint not null, bank_account_id bigint not null) engine=MyISAM;
create table user_contacts (user_id bigint not null, contacts_id bigint not null) engine=MyISAM;
create table user_transaction_users (user_id bigint not null, transaction_users_id bigint not null) engine=MyISAM;
alter table bank_account_bank_transactions add constraint UK_pgosd3tpquobn15aehke44j1g unique (bank_transactions_id);
alter table user_bank_account add constraint UK_n9nh18vaauto6bmi0p7ft8d4t unique (bank_account_id);
alter table user_transaction_users add constraint UK_6av3g4ea5w0lodnfhsp9d3l1c unique (transaction_users_id);
alter table bank_account add constraint FK92iik4jwhk7q385jubl2bc2mm foreign key (user_id) references user (id);
alter table bank_account_bank_transactions add constraint FK33paubx4rf8p5gj78h09r0k4u foreign key (bank_transactions_id) references transaction_bank (id);
alter table bank_account_bank_transactions add constraint FK93gtqw1lvfa10wpomw2yooxhs foreign key (bank_account_id) references bank_account (id);
alter table transaction_app add constraint FKf1gfaleqtl3di35sf0m8n2yiy foreign key (receiver_id) references user (id);
alter table transaction_app add constraint FK49j619uxo0m0p4ef9furm6hee foreign key (sender_id) references user (id);
alter table transaction_bank add constraint FKfsk86ieivf1trs79rd6huoxn3 foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FK32bq0igatas1bm9d7cj3emdmn foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FKjn71dv46t5vlrjbqroobqfxcl foreign key (user_id) references user (id);
alter table user_contacts add constraint FKbgjq1pj3f4kamou79l7cl87ne foreign key (contacts_id) references user (id);
alter table user_contacts add constraint FKmo0c5ro6kunnfq71x4bcwb9eh foreign key (user_id) references user (id);
alter table user_transaction_users add constraint FK7v441wsn0ldj19rgotmivv2tr foreign key (transaction_users_id) references transaction_app (id);
alter table user_transaction_users add constraint FKmjck60wbahp4thmrd6dd2gxiq foreign key (user_id) references user (id);
create table bank_account (id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=MyISAM;
create table bank_account_bank_transactions (bank_account_id bigint not null, bank_transactions_id bigint not null) engine=MyISAM;
create table transaction_app (id bigint not null auto_increment, transfered_amount float, date date not null, receiver_id bigint, sender_id bigint, primary key (id)) engine=MyISAM;
create table transaction_bank (id bigint not null auto_increment, transfered_amount float not null, date date not null, bank_account_id bigint, primary key (id)) engine=MyISAM;
create table user (id bigint not null auto_increment, amount_app_account float not null, email_adress varchar(255) not null, password varchar(255) not null, primary key (id)) engine=MyISAM;
create table user_bank_account (user_id bigint not null, bank_account_id bigint not null) engine=MyISAM;
create table user_contacts (user_id bigint not null, contacts_id bigint not null) engine=MyISAM;
create table user_transaction_users (user_id bigint not null, transaction_users_id bigint not null) engine=MyISAM;
alter table bank_account_bank_transactions add constraint UK_pgosd3tpquobn15aehke44j1g unique (bank_transactions_id);
alter table user_bank_account add constraint UK_n9nh18vaauto6bmi0p7ft8d4t unique (bank_account_id);
alter table user_transaction_users add constraint UK_6av3g4ea5w0lodnfhsp9d3l1c unique (transaction_users_id);
alter table bank_account add constraint FK92iik4jwhk7q385jubl2bc2mm foreign key (user_id) references user (id);
alter table bank_account_bank_transactions add constraint FK33paubx4rf8p5gj78h09r0k4u foreign key (bank_transactions_id) references transaction_bank (id);
alter table bank_account_bank_transactions add constraint FK93gtqw1lvfa10wpomw2yooxhs foreign key (bank_account_id) references bank_account (id);
alter table transaction_app add constraint FKf1gfaleqtl3di35sf0m8n2yiy foreign key (receiver_id) references user (id);
alter table transaction_app add constraint FK49j619uxo0m0p4ef9furm6hee foreign key (sender_id) references user (id);
alter table transaction_bank add constraint FKfsk86ieivf1trs79rd6huoxn3 foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FK32bq0igatas1bm9d7cj3emdmn foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FKjn71dv46t5vlrjbqroobqfxcl foreign key (user_id) references user (id);
alter table user_contacts add constraint FKbgjq1pj3f4kamou79l7cl87ne foreign key (contacts_id) references user (id);
alter table user_contacts add constraint FKmo0c5ro6kunnfq71x4bcwb9eh foreign key (user_id) references user (id);
alter table user_transaction_users add constraint FK7v441wsn0ldj19rgotmivv2tr foreign key (transaction_users_id) references transaction_app (id);
alter table user_transaction_users add constraint FKmjck60wbahp4thmrd6dd2gxiq foreign key (user_id) references user (id);
create table bank_account (id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=MyISAM;
create table bank_account_bank_transactions (bank_account_id bigint not null, bank_transactions_id bigint not null) engine=MyISAM;
create table transaction_app (id bigint not null auto_increment, transfered_amount float, date date not null, receiver_id bigint, sender_id bigint, primary key (id)) engine=MyISAM;
create table transaction_bank (id bigint not null auto_increment, transfered_amount float not null, date date not null, bank_account_id bigint, primary key (id)) engine=MyISAM;
create table user (id bigint not null auto_increment, amount_app_account float not null, email_adress varchar(255) not null, password varchar(255) not null, primary key (id)) engine=MyISAM;
create table user_bank_account (user_id bigint not null, bank_account_id bigint not null) engine=MyISAM;
create table user_contacts (user_id bigint not null, contacts_id bigint not null) engine=MyISAM;
create table user_transaction_users (user_id bigint not null, transaction_users_id bigint not null) engine=MyISAM;
alter table bank_account_bank_transactions add constraint UK_pgosd3tpquobn15aehke44j1g unique (bank_transactions_id);
alter table user_bank_account add constraint UK_n9nh18vaauto6bmi0p7ft8d4t unique (bank_account_id);
alter table user_transaction_users add constraint UK_6av3g4ea5w0lodnfhsp9d3l1c unique (transaction_users_id);
alter table bank_account add constraint FK92iik4jwhk7q385jubl2bc2mm foreign key (user_id) references user (id);
alter table bank_account_bank_transactions add constraint FK33paubx4rf8p5gj78h09r0k4u foreign key (bank_transactions_id) references transaction_bank (id);
alter table bank_account_bank_transactions add constraint FK93gtqw1lvfa10wpomw2yooxhs foreign key (bank_account_id) references bank_account (id);
alter table transaction_app add constraint FKf1gfaleqtl3di35sf0m8n2yiy foreign key (receiver_id) references user (id);
alter table transaction_app add constraint FK49j619uxo0m0p4ef9furm6hee foreign key (sender_id) references user (id);
alter table transaction_bank add constraint FKfsk86ieivf1trs79rd6huoxn3 foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FK32bq0igatas1bm9d7cj3emdmn foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FKjn71dv46t5vlrjbqroobqfxcl foreign key (user_id) references user (id);
alter table user_contacts add constraint FKbgjq1pj3f4kamou79l7cl87ne foreign key (contacts_id) references user (id);
alter table user_contacts add constraint FKmo0c5ro6kunnfq71x4bcwb9eh foreign key (user_id) references user (id);
alter table user_transaction_users add constraint FK7v441wsn0ldj19rgotmivv2tr foreign key (transaction_users_id) references transaction_app (id);
alter table user_transaction_users add constraint FKmjck60wbahp4thmrd6dd2gxiq foreign key (user_id) references user (id);
create table bank_account (id bigint not null auto_increment, user_id bigint not null, primary key (id)) engine=MyISAM;
create table bank_account_bank_transactions (bank_account_id bigint not null, bank_transactions_id bigint not null) engine=MyISAM;
create table transaction_app (id bigint not null auto_increment, transfered_amount float, date date not null, receiver_id bigint, sender_id bigint, primary key (id)) engine=MyISAM;
create table transaction_bank (id bigint not null auto_increment, transfered_amount float not null, date date not null, bank_account_id bigint, primary key (id)) engine=MyISAM;
create table user (id bigint not null auto_increment, amount_app_account float not null, email_adress varchar(255) not null, password varchar(255) not null, primary key (id)) engine=MyISAM;
create table user_bank_account (user_id bigint not null, bank_account_id bigint not null) engine=MyISAM;
create table user_contacts (user_id bigint not null, contacts_id bigint not null) engine=MyISAM;
create table user_transaction_users (user_id bigint not null, transaction_users_id bigint not null) engine=MyISAM;
alter table bank_account_bank_transactions add constraint UK_pgosd3tpquobn15aehke44j1g unique (bank_transactions_id);
alter table user_bank_account add constraint UK_n9nh18vaauto6bmi0p7ft8d4t unique (bank_account_id);
alter table user_transaction_users add constraint UK_6av3g4ea5w0lodnfhsp9d3l1c unique (transaction_users_id);
alter table bank_account add constraint FK92iik4jwhk7q385jubl2bc2mm foreign key (user_id) references user (id);
alter table bank_account_bank_transactions add constraint FK33paubx4rf8p5gj78h09r0k4u foreign key (bank_transactions_id) references transaction_bank (id);
alter table bank_account_bank_transactions add constraint FK93gtqw1lvfa10wpomw2yooxhs foreign key (bank_account_id) references bank_account (id);
alter table transaction_app add constraint FKf1gfaleqtl3di35sf0m8n2yiy foreign key (receiver_id) references user (id);
alter table transaction_app add constraint FK49j619uxo0m0p4ef9furm6hee foreign key (sender_id) references user (id);
alter table transaction_bank add constraint FKfsk86ieivf1trs79rd6huoxn3 foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FK32bq0igatas1bm9d7cj3emdmn foreign key (bank_account_id) references bank_account (id);
alter table user_bank_account add constraint FKjn71dv46t5vlrjbqroobqfxcl foreign key (user_id) references user (id);
alter table user_contacts add constraint FKbgjq1pj3f4kamou79l7cl87ne foreign key (contacts_id) references user (id);
alter table user_contacts add constraint FKmo0c5ro6kunnfq71x4bcwb9eh foreign key (user_id) references user (id);
alter table user_transaction_users add constraint FK7v441wsn0ldj19rgotmivv2tr foreign key (transaction_users_id) references transaction_app (id);
alter table user_transaction_users add constraint FKmjck60wbahp4thmrd6dd2gxiq foreign key (user_id) references user (id);
